### ISSUE TITLE
Error: cannot find type `Sqlite` in crate `sqlx` label: not found in `sqlx`

### ISSUE THREAD

**Issue by Chu-4hun** [treydempsey/sqlx-crud#8]
```
src
│   auth.rs
│   main.rs
│
└───models
        mod.rs
        user.rs
```
code inside ```user.rs```
```rs
use serde::{Serialize, Deserialize};
use sqlx::FromRow;
use sqlx_crud::SqlxCrud;

#[derive(Serialize, Deserialize, FromRow,)]
pub struct User {
    pub user_name: String,
    pub pass: String,
    pub email: String,
}


#[derive(Serialize, Deserialize,FromRow,SqlxCrud)] //error: cannot find type `Sqlite` in crate `sqlx` label: not found in `sqlx`
pub struct DbUser {
    pub id: i32,
    pub user_name: String,
    pub pass: String,
    pub email: String,
}
```

Cargo.toml
```toml
[package]
name = "rust_ani"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
dotenv = "0.15.0"
chrono = { version = "0.4.22", features = ["serde"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
sqlx = { version = "^0.6.2", features = ["postgres", "runtime-actix-native-tls", "chrono", "json", "macros"] }
sqlx-crud = { version = "0.3.2", features = ["runtime-actix-native-tls"], default-features = false }

actix-web-httpauth = "0.8.0"
jwt = "0.16.0"
hmac = "0.12.1"
argon2 = "0.4.1"
sha2 = "0.10.6"

```
without ``` default-features = false ``` it wont compile even when i use features flag
```rust
[ERROR rust_analyzer::lsp_utils] failed to run build scripts:
error: only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', 'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', 'runtime-tokio-rustls'] can be enabled
  --> C:\Users\danPC\.cargo\registry\src\github.com-1ecc6299db9ec823\sqlx-rt-0.6.2\src\lib.rs:23:1
   |
23 | / compile_error!(
24 | |     "only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
25 | |      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
26 | |      'runtime-tokio-rustls'] can be enabled"
27 | | );
   | |_^

```

**Comment by zoranzaric-cpx** [comment]
@Chu-4hun how did you fix this?
I'm trying to use sqlx-crud with postgres, too.

**Comment by Chu-4hun** [comment]
> @Chu-4hun how did you fix this?
> I'm trying to use sqlx-crud with postgres, too.

When I tried I couldn't get it to work. I looked into macro and it had sql lite specific syntax. So, back to manual CRUDs.

**Comment by Chu-4hun** [comment]
> @Chu-4hun how did you fix this?
> I'm trying to use sqlx-crud with postgres, too.

Even all examples are with sql lite

**Comment by zoranzaric-cpx** [comment]
Ok, thanks. I managed to get it working locally with tweaking the `sqlx-crud` code. I'll try to generalize it and create a PR.

@treydempsey are you open for PRs?

**Comment by MattDelac** [comment]
> Ok, thanks. I managed to get it working locally with tweaking the `sqlx-crud` code. I'll try to generalize it and create a PR.
> 
> @treydempsey are you open for PRs?

@zoranzaric-cpx did you end up fixing it? I am running into the same issue and it seems that sqlx-crud only works with Sqlite as of now

**Comment by MattDelac** [comment]
@zoranzaric-cpx I see your PR from 2023 https://github.com/treydempsey/sqlx-crud/pull/12 ...

That tells me that this crate is just not maintained while a lot of people have interest in it. @zoranzaric-cpx @Chu-4hun do you want us to fork it and collaborate together? We could easily support MySQL, Postgres and Sqlite.

**Comment by Chu-4hun** [comment]
> @zoranzaric-cpx I see your PR from 2023 https://github.com/treydempsey/sqlx-crud/pull/12 ...
> 
> That tells me that this crate is just not maintained while a lot of people have interest in it. @zoranzaric-cpx @Chu-4hun do you want us to fork it and collaborate together? We could easily support MySQL, Postgres and Sqlite.

The could be nice. But I don't use it since issue was created

**Comment by AizenSosike** [comment]
I found that your sqlx features dont include "sqllite" . I have met same issue but I'm using "mysql" , It works when I add it to the features

**Comment by MattDelac** [comment]
@zoranzaric-cpx @Chu-4hun @AizenSosike I created an alternative over the weekend. Feel free to check it out and tell me what you think https://github.com/MattDelac/tiny_orm
